### ISSUE TITLE
Design a starting phase of the website.

### ISSUE THREAD

**Issue by harshit98** [Jaipur-Open-Source-Community/jaipuropensource.github.io#1]
Design the website for the Jaipur Open Source community using jekyll. Once the structure is ready, we will open up several other issues related to enhancements on the website with label `hacktoberfest` as well.

**Comment by Prakhar0409** [comment]
Going to jump on this for hacktoberfest. Please read this as assigned:)

**Comment by harshit98** [comment]
Hi @Prakhar0409. Sure. Thanks for contributing. I'm assigning this issue to you. Please open up the separate issues you'll face during the development. I will mark them with the `hacktoberfest` label. :)
